# Generated by Django 4.1.5 on 2023-02-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='matching_pecentage',
            field=models.IntegerField(),
        ),
    ]
