# Generated by Django 4.1.6 on 2023-02-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_addtionalinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionalinfomodel',
            name='fluency',
            field=models.IntegerField(null=True),
        ),
    ]
