# Generated by Django 4.1.5 on 2023-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_room_matching_pecentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='matching_pecentage',
        ),
        migrations.AddField(
            model_name='room',
            name='matching_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
